Vagrant.configure("2") do |config|
  # config为全局配置文件
  config.vm.box = "ubuntu/trusty64"
  # 定义VS
  config.vm.define "vs" do |vs|
    config.vm.network "private_network", ip: "192.168.50.4"
    vs.vm.hostname = "vs"
  end
  # 定义RS1
  config.vm.define "rs1" do |rs1|
    rs1.vm.network "private_network", ip: "192.168.50.5"
    rs1.vm.hostname = "rs1"
  end
  # 定义RS2
  config.vm.define "rs2" do |rs2|
    rs2.vm.network "private_network", ip: "192.168.50.6"
    rs2.vm.hostname = "rs2"
  end
end
