Vagrant.configure("2") do |config|
  config.vm.box = "bento/fedora-31"
  config.vm.provider "virtualbox" do |v|
    v.name = "fedora31_box"
    v.memory = 1024
    v.cpus = 1
  end
  config.vm.hostname = "lailab"
end
