Vagrant.configure("2") do |config|
  config.vm.box = "bento/fedora-31"
  config.vm.provider "virtualbox" do |v|
    v.name = "fedora31_box"
    v.memory = 1024
    v.cpus = 1
  end
  config.vm.hostname = "lailab"

  config.vm.network "private_network", type: "dhcp"

  config.vm.provision "shell", privileged: true, inline: <<-SHELL
    echo 'proxy=http://10.0.2.2:7890' >> /etc/dnf/dnf.conf
    dnf install -y nmap iproute htop man-pages
  SHELL
end
