# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|
    os = "bento/ubuntu-22.04"

    config.vm.provider "virtualbox" do |vb|
        vb.memory = "2048"
        vb.cpus = 4
    end

    config.vm.define "host1" do |host1|
      host1.vm.box = "#{os}"
      host1.vm.host_name = "ubuntu.private"
      host1.vm.define "base-ubuntu"
      host1.vm.network "private_network", type: "dhcp"
    end

    config.vm.define "host2" do |host2|
      host2.vm.box = "#{os}"
      host2.vm.host_name = "ubuntu.private"
      host2.vm.define "base-ubuntu"
      host2.vm.network "private_network", type: "dhcp"
    end
end
