# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|
    os = "ubuntu/trusty64"

    config.vm.provider "virtualbox" do |vb|
        vb.memory = "8192"
        vb.cpus = 4
        vb.name = "kibana"
    end
    config.vm.box = "#{os}"
    config.vm.host_name = "ubuntu.private"
    config.vm.define "base-ubuntu"
    config.vm.network "private_network", type: "dhcp"
end
