# vim: filetype=ruby

# host => guest
forward_ports = {
  8087 => 8080,
  7687 => 7687,
  7474 => 7474,
}

Vagrant.configure("2") do |config|
    config.vm.box = "bento/ubuntu-22.04"
    config.vm.provider "virtualbox" do |v|
        v.memory = 4096
        v.cpus = 4
    end

    config.vm.host_name = "foobarhost"
    config.vm.define "foobar"

    config.vm.provider :virtualbox do |vb|
        vb.name = "foobar"
    end

    forward_ports.each do |host_port, guest_port|
      config.vm.network :forwarded_port, host: host_port, guest: guest_port
    end

end
