# vim: filetype=ruby
Vagrant.configure("2") do |config|
    config.vm.box = "bento/ubuntu-22.04"
    config.vm.provider "virtualbox" do |v|
        v.memory = 4096
        v.cpus = 4
    end

    config.vm.host_name = "foobarhost"
    config.vm.define "foobar"

    config.vm.provider :virtualbox do |vb|
        vb.name = "foobar"
    end

end
