# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|
    os = "nrel/CentOS-6.5-x86_64"

    config.vm.provider "virtualbox" do |vb|
        vb.memory = "2048"
        vb.cpus = 2
        vb.name = "try_tair"
    end
    config.vm.box = "#{os}"
    config.vm.host_name = "tair.main"
    config.vm.define "tair_on_centos"
    config.vm.network "public_network"
end
